### ISSUE TITLE
how do start learn java

### ISSUE THREAD

**Issue by gladiusglad** [NotAShelf/notashelf#1]
helo me gladius want to learn jaav lik you but idk how too??? pls teach

**Comment by NotAShelf** [comment]
yes hello gladius
im very wise java man and i will teach you how


use [this link](https://www.google.com/search?sxsrf=ALeKk02L9QdWL1Kw7wEwDfXNY5nxXCEELg%3A1606313024667&source=hp&ei=QGS-X7_2JMHwaLyGorAK&q=how+to+learn+java&oq=how+to+learn+java&gs_lcp=CgZwc3ktYWIQAzIICAAQyQMQywEyBQgAEMsBMgUIABDLATIFCAAQywEyAggAMgIIADICCAAyAggAMgIIADICCAA6BAgjECc6CAgAEMkDEJECOgUIABCRAjoICC4QxwEQowI6AgguOgcIABAUEIcCOg0ILhDJAxAKEMsBEJMCOgQIABAKOgQILhAKOgUILhDLAToKCAAQyQMQFBCHAlCXBFj3G2DAHGgCcAB4AIABqQGIAawTkgEEMC4xOJgBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwi_luup7p3tAhVBOBoKHTyDCKYQ4dUDCAY&uact=5)
